# Helpers integration
helpers:
  # Helper Operator para instalar Red Hat Pipelines operator
  operator:
    enabled: true
    operators:
      # Red Hat OpenShift Pipelines (Tekton)
      openshift-pipelines-operator:
        enabled: true
        syncwave: 0
        namespace:
          name: openshift-operators
          create: false
        subscription:
          channel: latest
          operatorName: openshift-pipelines-operator-rh
          source: redhat-operators
        operatorgroup:
          create: false
          notownnamespace: true
          

  # Status Checker para health monitoring
  statusChecker:
    enabled: true
    statusChecks:
      checks:
        pipelines-operator:
          enabled: true
          type: deployment
          namespace: openshift-pipelines
          name: tekton-pipelines-controller
        tekton-triggers:
          enabled: true
          type: deployment
          namespace: openshift-pipelines
          name: tekton-triggers-controller

# Pipeline Configuration
pipelines:
  # Namespace donde se ejecutarán las pipelines por defecto
  defaultNamespace: "openshift-pipelines-runs"
  
  # Configuraciones por defecto para las pipelines
  defaults:
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "512Mi"
        cpu: "500m"
    
    # Timeout por defecto para las tareas (en minutos)
    defaultTimeout: 60
    
    # Storage por defecto para workspaces
    defaultWorkspaceSize: "1Gi"

# Tekton Configuration (OpenShift Pipelines)
tekton:
  # TektonConfig - Main configuration for the cluster
  config:
    enabled: true
    targetNamespace: openshift-pipelines
    
    # Global parameters for TektonConfig
    params:
      - name: createRbacResource
        value: "true"
      - name: defaultServiceAccount
        value: "pipeline"
      - name: defaultTimeout
        value: "60m"
      - name: defaultManagedByLabelValue
        value: "tekton-pipelines"
      - name: defaultPodTemplate
        value: |
          nodeSelector:
            kubernetes.io/os: linux
          tolerations:
          - key: "kubernetes.io/arch"
            operator: "Equal"
            value: "amd64"
            effect: "NoSchedule"

  # Tekton Pipelines component
  pipeline:
    enabled: true
    params:
      - name: enable-api-fields
        value: "beta"
      - name: enable-tekton-oci-bundles
        value: "true"
      - name: enable-custom-tasks
        value: "true"
      - name: enable-provenance-in-status
        value: "true"
      - name: trusted-resources-verification-no-match-policy
        value: "warn"
    
    # Performance tuning
    performance:
      replicas: 2
      buckets: 10
      kmsKeyName: ""
      threadPoolSize: 10

  # Tekton Triggers component
  trigger:
    enabled: true
    params:
      - name: enable-api-fields
        value: "beta"

  # Tekton Dashboard component
  dashboard:
    enabled: true
    readonly: false
    params:
      - name: enable-logout
        value: "true"
      - name: enable-log-streaming
        value: "true"

  # Tekton Hub component
  hub:
    enabled: false  # Usually disabled in enterprise environments
    params:
      - name: enable-devconsole-integration
        value: "true"

  # Tekton Chains component (for supply chain security)
  chains:
    enabled: true
    params:
      - name: artifacts.taskrun.format
        value: "tekton"
      - name: artifacts.taskrun.storage
        value: "oci"
      - name: artifacts.oci.storage
        value: "oci"
      - name: transparency.enabled
        value: "false"


# Security Context (Enterprise Best Practices)
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1001
  runAsGroup: 1001
  fsGroup: 1001
  seccompProfile:
    type: RuntimeDefault

securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1001
  runAsGroup: 1001
  capabilities:
    drop:
    - ALL

# Service Account
serviceAccount:
  create: true
  annotations: {}
  name: ""
  automountServiceAccountToken: false

# Network Policy
networkPolicy:
  enabled: true
  ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            name: openshift-gitops
      - namespaceSelector:
          matchLabels:
            name: rhop-pipelines
      ports:
      - protocol: TCP
        port: 8080

# Resource requests and limits
resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

# Node selection
nodeSelector: {}

# Tolerations
tolerations: []

# Pod affinity
affinity: {}