# Helpers integration
helpers:
  # Helper Operator para instalar RHDH operator
  operator:
    enabled: true
    operators:
      rhdh-operator:
        enabled: true
        syncwave: 0
        namespace:
          name: openshift-operators
        subscription:
          channel: stable
          operatorName: rhdh-operator
          source: redhat-operators

  # Status Checker para health monitoring del operador
  statusChecker:
    enabled: true
    statusChecks:
      checks:
        rhdh-operator:
          enabled: true
          type: deployment
          namespace: openshift-operators
          name: rhdh-operator

# Configuración básica del operador
operator:
  # Namespace por defecto donde se pueden crear instancias RHDH
  defaultNamespace: "rhdh"