apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      securityContext:
        fsGroup: 1000 # Asegura que los archivos sean accesibles por el grupo 1000
      containers:
      - name: gitea
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - containerPort: 3000
        - containerPort: 22
        volumeMounts:
        - name: gitea-data
          mountPath: /data
        env:
        - name: USER_UID
          value: "{{ .Values.user.uid }}"
        - name: USER_GID
          value: "{{ .Values.user.gid }}"
        {{- if .Values.oauth.enabled }}
        - name: OAUTH2_ENABLE
          value: "true"
        - name: OAUTH2_OPENID_PROVIDER
          value: "{{ .Values.oauth.provider }}"
        - name: OAUTH2_OPENID_CLIENT_ID
          value: "{{ .Values.oauth.clientId }}"
        - name: OAUTH2_OPENID_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ .Values.oauth.secretName }}
              key: clientSecret
        - name: OAUTH2_OPENID_CONNECT_AUTO_DISCOVER_URL
          value: "{{ .Values.oauth.autoDiscoverUrl }}"
        {{- end }}
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000940000
          fsGroup: 1000940000
          allowPrivilegeEscalation: false # Previene la escalación de privilegios
          capabilities:
            drop:
              - ALL # Elimina todas las capacidades no necesarias
          seccompProfile:
            type: RuntimeDefault # Usa el perfil de seccomp predeterminado
      volumes:
      - name: gitea-data
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-data
