apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "setup-platform-gitea.fullname" . }}-config
  namespace: {{ .Values.namespace.name }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    {{- include "setup-platform-gitea.labels" . | nindent 4 }}
data:
  app.ini: |
    APP_NAME = {{ .Values.config.appName | default "Gitea Git Server" }}
    RUN_MODE = {{ .Values.config.runMode | default "prod" }}
    RUN_USER = git
    WORK_PATH = /tmp/gitea

    [database]
    DB_TYPE  = postgres
    HOST     = {{ .Release.Name }}-postgresql.{{ .Values.namespace.name }}.svc.cluster.local:5432
    NAME     = {{ .Values.postgresql.auth.database }}
    USER     = {{ .Values.postgresql.auth.username }}
    PASSWD   = {{ .Values.postgresql.auth.password }}
    SCHEMA   = 
    SSL_MODE = disable
    CHARSET  = utf8

    [repository]
    ROOT = /data/git/repositories
    SCRIPT_TYPE = bash
    DEFAULT_BRANCH = main
    FORCE_PRIVATE = false
    DEFAULT_PRIVATE = last
    MAX_CREATION_LIMIT = -1
    MIRROR_QUEUE_LENGTH = 1000
    PULL_REQUEST_QUEUE_LENGTH = 1000
    PREFERRED_LICENSES = Apache License 2.0,MIT License
    DISABLE_HTTP_GIT = false
    ACCESS_CONTROL_ALLOW_ORIGIN = 
    USE_COMPAT_SSH_URI = false
    DEFAULT_CLOSE_ISSUES_VIA_COMMITS_IN_ANY_BRANCH = false

    [ui]
    EXPLORE_PAGING_NUM = 20
    ISSUE_PAGING_NUM = 20
    MEMBERS_PAGING_NUM = 20
    FEED_MAX_COMMIT_NUM = 5
    GRAPH_MAX_COMMIT_NUM = 100
    CODE_COMMENT_LINES = 4
    DEFAULT_SHOW_FULL_NAME = false
    SEARCH_REPO_DESCRIPTION = true
    USE_SERVICE_WORKER = false

    [ui.admin]
    USER_PAGING_NUM = 50
    REPO_PAGING_NUM = 50
    NOTICE_PAGING_NUM = 25
    ORG_PAGING_NUM = 50

    [ui.user]
    REPO_PAGING_NUM = 15

    [ui.meta]
    AUTHOR = {{ .Values.config.appName | default "Gitea Git Server" }}
    DESCRIPTION = Git with a cup of tea! A painless self-hosted Git service.
    KEYWORDS = go,git,self-hosted,gitea

    [markdown]
    ENABLE_HARD_LINE_BREAK_IN_COMMENTS = true
    ENABLE_HARD_LINE_BREAK_IN_DOCUMENTS = false
    CUSTOM_URL_SCHEMES = 
    FILE_EXTENSIONS = .md,.markdown,.mdown,.mkd,.livemd

    [server]
    PROTOCOL = http
    DOMAIN = {{ .Values.route.host | default "gitea.local" }}
    ROOT_URL = https://{{ .Values.route.host | default "gitea.local" }}/
    HTTP_ADDR = 0.0.0.0
    HTTP_PORT = 3000
    REDIRECT_OTHER_PORT = false
    DISABLE_SSH = {{ .Values.config.disableSSH | default "true" }}
    START_SSH_SERVER = false
    SSH_DOMAIN = {{ .Values.route.host | default "gitea.local" }}
    SSH_PORT = 22
    SSH_LISTEN_PORT = 22
    OFFLINE_MODE = false
    DISABLE_ROUTER_LOG = false
    CERT_FILE = 
    KEY_FILE = 
    STATIC_ROOT_PATH = 
    ENABLE_GZIP = false
    ENABLE_PPROF = false
    PPROF_DATA_PATH = data/tmp/pprof
    LANDING_PAGE = home
    LFS_START_SERVER = true

    [ssh.minimum_key_sizes]
    ED25519 = 256
    ECDSA   = 256
    RSA     = 2047
    DSA     = -1

    [security]
    INSTALL_LOCK                  = true
    SECRET_KEY                    = {{ randAlphaNum 43 | b64enc }}
    LOGIN_REMEMBER_DAYS           = 7
    COOKIE_USERNAME               = gitea_awesome
    COOKIE_REMEMBER_NAME          = gitea_incredible
    REVERSE_PROXY_AUTHENTICATION  = false
    REVERSE_PROXY_AUTO_REGISTRATION = false
    DISABLE_GIT_HOOKS             = true
    ONLY_ALLOW_PUSH_IF_GITEA_ENVIRONMENT_SET = true

    [service]
    ACTIVE_CODE_LIVE_MINUTES = 180
    RESET_PASSWD_CODE_LIVE_MINUTES = 180
    REGISTER_EMAIL_CONFIRM = false
    REGISTER_MANUAL_CONFIRM = false
    ENABLE_NOTIFY_MAIL = false
    DISABLE_REGISTRATION = false
    ALLOW_ONLY_EXTERNAL_REGISTRATION = false
    ENABLE_CAPTCHA = false
    REQUIRE_SIGNIN_VIEW = false
    DEFAULT_KEEP_EMAIL_PRIVATE = false
    DEFAULT_ALLOW_CREATE_ORGANIZATION = true
    DEFAULT_ENABLE_TIMETRACKING = true
    NO_REPLY_ADDRESS = noreply.{{ .Values.route.host | default "gitea.local" }}

    [picture]
    DISABLE_GRAVATAR        = true
    ENABLE_FEDERATED_AVATAR = false

    [openid]
    ENABLE_OPENID_SIGNIN = false
    ENABLE_OPENID_SIGNUP = false

    [session]
    PROVIDER = file
    PROVIDER_CONFIG = /tmp/gitea/data/sessions
    COOKIE_SECURE = false
    COOKIE_NAME = i_like_gitea
    GC_INTERVAL_TIME = 86400
    SESSION_LIFE_TIME = 86400

    [log]
    MODE = console
    LEVEL = info
    ROOT_PATH = /tmp/gitea/log
    ENABLE_XORM_LOG = false

    [git]
    PATH = 
    DISABLE_DIFF_HIGHLIGHT = false
    MAX_GIT_DIFF_LINES = 1000
    MAX_GIT_DIFF_LINE_CHARACTERS = 5000
    MAX_GIT_DIFF_FILES = 100
    GC_ARGS = 

    [git.timeout]
    DEFAULT = 360
    MIGRATE = 600
    MIRROR = 300
    CLONE = 300
    PULL = 300
    GC = 60

    [mirror]
    DEFAULT_INTERVAL = 8h
    MIN_INTERVAL = 10m

    [api]
    ENABLE_SWAGGER = true
    MAX_RESPONSE_ITEMS = 50
    DEFAULT_PAGING_NUM = 30
    DEFAULT_GIT_TREES_PER_PAGE = 1000
    DEFAULT_MAX_BLOB_SIZE = 10485760

    [oauth2]
    ENABLE = false

    [i18n]
    LANGS = en-US,zh-CN,zh-HK,zh-TW,de-DE,fr-FR,nl-NL,lv-LV,ru-RU,uk-UA,ja-JP,es-ES,pt-BR,pt-PT,pl-PL,bg-BG,it-IT,fi-FI,tr-TR,cs-CZ,sr-SP,sv-SE,ko-KR,el-GR,fa-IR,hu-HU,id-ID,ml-IN
    NAMES = English,简体中文,繁體中文（香港）,繁體中文（台灣）,Deutsch,français,Nederlands,latviešu,русский,Українська,日本語,español,português do Brasil,Português de Portugal,polski,български,italiano,suomi,Türkçe,čeština,српски,svenska,한국어,ελληνικά,فارسی,magyar nyelv,bahasa Indonesia,മലയാളം

    [indexer]
    ISSUE_INDEXER_PATH = /tmp/gitea/indexers/issues.bleve
    ISSUE_INDEXER_TYPE = bleve
    ISSUE_INDEXER_CONN_STR =
    ISSUE_INDEXER_NAME = gitea_issues
    REPO_INDEXER_ENABLED = false
    REPO_INDEXER_PATH = /tmp/gitea/indexers/repos.bleve
    REPO_INDEXER_INCLUDE = 
    REPO_INDEXER_EXCLUDE = 
    REPO_INDEXER_EXCLUDE_VENDORED = true
    MAX_FILE_SIZE = 1048576

    [admin]
    DISABLE_REGULAR_ORG_CREATION = false

    [webhook]
    QUEUE_LENGTH = 1000
    DELIVER_TIMEOUT = 5
    SKIP_TLS_VERIFY = false
    ALLOWED_HOST_LIST = 
    PAGING_NUM = 10
    PROXY_URL = 
    PROXY_HOSTS = *.local,127.*,192.168.*

    [mailer]
    ENABLED = false

    [cache]
    ENABLED = true
    ADAPTER = memory
    INTERVAL = 60
    HOST = 
    ITEM_TTL = 16h

    [attachment]
    ENABLED = true
    ALLOWED_TYPES = image/jpeg,image/png,application/zip,application/gzip
    MAX_SIZE = 4
    MAX_FILES = 5
    STORAGE_TYPE = local
    PATH = /tmp/gitea/data/attachments

    [time]
    DEFAULT_UI_LOCATION = UTC

    [cron.update_checker]
    ENABLED = false

    [repository.editor]
    LINE_WRAP_EXTENSIONS = .txt,.md,.markdown,.mdown,.mkd,.livemd

    [repository.local]
    LOCAL_COPY_PATH = /tmp/gitea/tmp/local-repo

    [repository.upload]
    TEMP_PATH = /tmp/gitea/data/tmp/uploads