apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "setup-platform-gitea.fullname" . }}
  namespace: {{ .Values.namespace.name }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    {{- include "setup-platform-gitea.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "setup-platform-gitea.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "setup-platform-gitea.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "setup-platform-gitea.serviceAccountName" . }}
      initContainers:
        - name: init-data-directories
          image: registry.redhat.io/ubi9/ubi-minimal:latest
          command:
            - /bin/sh
            - -c
            - |
              mkdir -p /data/gitea/conf /data/gitea/log /data/git/repositories /data/git/.ssh /data/ssh
              touch /data/gitea/conf/app.ini
              touch /data/git/.ssh/environment
              chmod -R 777 /data
          volumeMounts:
            - name: data
              mountPath: /data
          securityContext:
            runAsUser: 0
            allowPrivilegeEscalation: true
      containers:
        - name: gitea
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
            - name: ssh
              containerPort: 22
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            - name: GITEA__database__DB_TYPE
              value: postgres
            - name: GITEA__repository__ROOT
              value: /data/git/repositories
            - name: GITEA__server__DOMAIN
              value: {{ .Values.route.host | default "gitea.local" }}
            - name: GITEA__server__HTTP_PORT
              value: "3000"
            - name: GITEA__server__ROOT_URL
              value: https://{{ .Values.route.host | default "gitea.local" }}
            # OpenShift compatibility - run as user 1001
            - name: USER_UID
              value: "1001"
            - name: USER_GID
              value: "1001"
            - name: RUN_MODE
              value: "prod"
            - name: GITEA__security__INSTALL_LOCK
              value: "false"
            - name: GITEA_WORK_DIR
              value: "/data"
            - name: GITEA_CUSTOM
              value: "/data/gitea"
            - name: GITEA__database__HOST
              value: "gitea-final-postgresql.gitea-final.svc.cluster.local:5432"
            - name: GITEA__database__NAME
              value: "gitea"
            - name: GITEA__database__USER
              value: "gitea"
            - name: GITEA__database__PASSWD
              value: "gitea-password"
            # Disable problematic features for OpenShift
            - name: GITEA__server__DISABLE_SSH
              value: "true"  # Disable SSH server to avoid port 22 issues
            - name: GITEA__security__DISABLE_GIT_HOOKS
              value: "true"
            - name: GITEA__log__ROOT_PATH
              value: "/data/gitea/log"
          volumeMounts:
            - name: data
              mountPath: /data
            - name: tmp
              mountPath: /tmp
            - name: var-lib-gitea
              mountPath: /var/lib/gitea
            - name: etc-passwd
              mountPath: /etc/passwd
              subPath: passwd
            - name: etc-group
              mountPath: /etc/group
              subPath: group
      volumes:
        - name: data
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "setup-platform-gitea.fullname" . }}-data
          {{- else }}
          emptyDir: 
            sizeLimit: 10Gi
          {{- end }}
        - name: tmp
          emptyDir:
            sizeLimit: 1Gi
        - name: var-lib-gitea
          emptyDir:
            sizeLimit: 500Mi
        - name: etc-passwd
          configMap:
            name: {{ include "setup-platform-gitea.fullname" . }}-passwd
        - name: etc-group
          configMap:
            name: {{ include "setup-platform-gitea.fullname" . }}-group
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}