{{- if .Values.namespace.create -}}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace.name }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    {{- include "setup-platform-gitea.labels" . | nindent 4 }}
    name: {{ .Values.namespace.name }}
{{- end -}}