apiVersion: v1
kind: Service
metadata:
  name: {{ include "setup-platform-gitea.fullname" . }}
  namespace: {{ .Values.namespace.name }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    {{- include "setup-platform-gitea.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 22
      targetPort: ssh
      protocol: TCP
      name: ssh
  selector:
    {{- include "setup-platform-gitea.selectorLabels" . | nindent 4 }}