apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "setup-app-openshift-ai-asistant.fullname" . }}
  namespace: {{ include "setup-app-openshift-ai-asistant.namespace" . }}
  labels:
    {{- include "setup-app-openshift-ai-asistant.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "setup-app-openshift-ai-asistant.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "setup-app-openshift-ai-asistant.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ include "setup-app-openshift-ai-asistant.serviceAccountName" . }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: ai-assistant
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
          - name: QUARKUS_PROFILE
            value: "prod"
          - name: OPENSHIFT_AI_ENDPOINT
            value: {{ .Values.openshift.ai.endpoint | quote }}
          - name: OPENSHIFT_AI_MODEL
            value: {{ .Values.openshift.ai.model | quote }}
          - name: BOOKSTACK_URL
            value: {{ .Values.external.bookstack.url | quote }}
          - name: GITEA_URL
            value: {{ .Values.external.gitea.url | quote }}
          - name: KEYCLOAK_URL
            value: {{ .Values.external.keycloak.url | quote }}
          {{- if .Values.postgresql.enabled }}
          - name: DATABASE_URL
            value: "postgresql://{{ .Values.postgresql.auth.username }}:{{ .Values.postgresql.auth.password }}@{{ include "setup-app-openshift-ai-asistant.fullname" . }}-postgresql:5432/{{ .Values.postgresql.auth.database }}"
          {{- end }}
          {{- if .Values.redis.enabled }}
          - name: REDIS_URL
            value: "redis://{{ include "setup-app-openshift-ai-asistant.fullname" . }}-redis-master:6379"
          {{- end }}
          {{- if .Values.qdrant.enabled }}
          - name: QDRANT_URL
            value: "http://{{ include "setup-app-openshift-ai-asistant.fullname" . }}-qdrant:6333"
          {{- end }}
          livenessProbe:
            httpGet:
              path: /q/health/live
              port: http
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /q/health/ready
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          - name: tmp
            mountPath: /tmp
          - name: cache
            mountPath: /app/cache
      volumes:
      - name: tmp
        emptyDir: {}
      - name: cache
        emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}