{{- if .Values.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "setup-app-openshift-ai-asistant.fullname" . }}
  namespace: {{ include "setup-app-openshift-ai-asistant.namespace" . }}
  labels:
    {{- include "setup-app-openshift-ai-asistant.labels" . | nindent 4 }}
  {{- with .Values.route.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.route.host }}
  host: {{ .Values.route.host }}
  {{- end }}
  to:
    kind: Service
    name: {{ include "setup-app-openshift-ai-asistant.fullname" . }}
    weight: 100
  port:
    targetPort: http
  {{- if .Values.route.tls }}
  tls:
    {{- toYaml .Values.route.tls | nindent 4 }}
  {{- end }}
  wildcardPolicy: None
{{- end }}