{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "setup-app-openshift-ai-asistant.serviceAccountName" . }}
  namespace: {{ include "setup-app-openshift-ai-asistant.namespace" . }}
  labels:
    {{- include "setup-app-openshift-ai-asistant.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
{{- end }}