{{- if .Values.keycloak.instance.enabled -}}
apiVersion: keycloak.org/v1alpha1
kind: Keycloak
metadata:
  name: {{ .Values.keycloak.instance.name }}
  namespace: {{ .Values.keycloak.namespace.name }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  labels:
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  instances: {{ .Values.keycloak.instance.replicas }}
  
  {{- if .Values.keycloak.database.external }}
  db:
    vendor: {{ .Values.keycloak.database.vendor }}
    host: {{ .Values.keycloak.database.host }}
    port: {{ .Values.keycloak.database.port }}
    database: {{ .Values.keycloak.database.name }}
    usernameSecret:
      name: {{ .Values.keycloak.database.credentialsSecret }}
      key: username
    passwordSecret:
      name: {{ .Values.keycloak.database.credentialsSecret }}
      key: password
  {{- end }}

  {{- if .Values.keycloak.hostname.enabled }}
  hostname:
    hostname: {{ .Values.keycloak.hostname.value }}
    {{- if .Values.keycloak.hostname.strict }}
    strict: true
    {{- end }}
  {{- end }}

  {{- if .Values.keycloak.http.enabled }}
  http:
    httpEnabled: {{ .Values.keycloak.http.httpEnabled }}
    {{- if .Values.keycloak.http.httpPort }}
    httpPort: {{ .Values.keycloak.http.httpPort }}
    {{- end }}
    {{- if .Values.keycloak.http.httpsPort }}
    httpsPort: {{ .Values.keycloak.http.httpsPort }}
    {{- end }}
  {{- end }}

  {{- if .Values.keycloak.resources }}
  resources:
    {{- toYaml .Values.keycloak.resources | nindent 4 }}
  {{- end }}

  {{- if .Values.keycloak.unsupported }}
  unsupported:
    podTemplate:
      {{- if .Values.keycloak.unsupported.podTemplate.metadata }}
      metadata:
        {{- toYaml .Values.keycloak.unsupported.podTemplate.metadata | nindent 8 }}
      {{- end }}
      {{- if .Values.keycloak.unsupported.podTemplate.spec }}
      spec:
        {{- toYaml .Values.keycloak.unsupported.podTemplate.spec | nindent 8 }}
      {{- end }}
  {{- end }}

  {{- if .Values.keycloak.additionalOptions }}
  additionalOptions:
    {{- range .Values.keycloak.additionalOptions }}
    - name: {{ .name }}
      value: {{ .value | quote }}
    {{- end }}
  {{- end }}
{{- end -}}