{{- if .Values.keycloak.instance.enabled -}}
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: {{ .Values.keycloak.instance.name }}
  namespace: {{ .Values.keycloak.namespace.name }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  labels:
    app: sso
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  instances: {{ .Values.keycloak.instance.replicas }}

  {{- if .Values.keycloak.networkPolicy.enabled }}
  networkPolicy:
    enabled: {{ .Values.keycloak.networkPolicy.enabled }}
  {{- end }}

  http:
    httpEnabled: true

  {{- if .Values.keycloak.update.strategy }}
  update:
    strategy: {{ .Values.keycloak.update.strategy }}
  {{- end }}

  {{- if .Values.keycloak.hostname.enabled }}
  hostname:
    hostname: {{ .Values.keycloak.hostname.value }}
    {{- if .Values.keycloak.hostname.strict }}
    strict: {{ .Values.keycloak.hostname.strict }}
    {{- end }}
  {{- end }}

  {{- if .Values.keycloak.database.external }}
  db:
    vendor: {{ .Values.keycloak.database.vendor }}
    host: {{ .Values.keycloak.database.host }}
    port: {{ .Values.keycloak.database.port }}
    database: {{ .Values.keycloak.database.name }}
    usernameSecret:
      name: {{ .Values.keycloak.database.credentialsSecret }}
      key: username
    passwordSecret:
      name: {{ .Values.keycloak.database.credentialsSecret }}
      key: password
  {{- end }}

  {{- if .Values.keycloak.resources }}
  resources:
    {{- toYaml .Values.keycloak.resources | nindent 4 }}
  {{- end }}

  {{- if .Values.keycloak.additionalOptions }}
  additionalOptions:
    {{- range .Values.keycloak.additionalOptions }}
    - name: {{ .name }}
      value: {{ .value | quote }}
    {{- end }}
  {{- end }}

  {{- if .Values.keycloak.unsupported }}
  unsupported:
    {{- toYaml .Values.keycloak.unsupported | nindent 4 }}
  {{- end }}
{{- end -}}