{{- if .Values.keycloak.namespace.create -}}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.keycloak.namespace.name }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    name: {{ .Values.keycloak.namespace.name }}
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- end -}}