{{- if .Values.sealedSecrets.namespace.create -}}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.sealedSecrets.namespace.name }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    name: {{ .Values.sealedSecrets.namespace.name }}
    app.kubernetes.io/name: sealed-secrets
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- end -}}