# Helpers integration
helpers:
  # Helper Operator para instalar RHBK operator
  operator:
    enabled: true
    operators:
      rhbk-operator:
        enabled: true
        syncwave: 0
        namespace:
          name: openshift-operators-redhat
        subscription:
          channel: stable
          operatorName: rhbk-operator
          source: redhat-operators

  # Status Checker para health monitoring del operador
  statusChecker:
    enabled: true
    statusChecks:
      checks:
        rhbk-operator:
          enabled: true
          type: deployment
          namespace: openshift-operators-redhat
          name: rhbk-operator

# Configuración básica del operador
operator:
  # Namespace por defecto donde se pueden crear instancias Keycloak
  defaultNamespace: "keycloak"