apiVersion: v1
kind: Namespace
metadata:
  name: bookstack
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    openshift.io/display-name: "Bookstack Documentation"
    openshift.io/description: "Corporate documentation platform"
    argocd.argoproj.io/managed: "true"
  labels:
    name: bookstack
    openshift.io/cluster-monitoring: "true"
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/audit: baseline
    pod-security.kubernetes.io/warn: baseline

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: bookstack-default-anyuid
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:anyuid
subjects:
- kind: ServiceAccount
  name: default
  namespace: bookstack
