{{- if .Values.documentation.enabled }}
{{- range $name, $repo := .Values.documentation.gitSync.repositories }}
{{- if and $repo.enabled $repo.secret $repo.credentials }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $repo.secret }}
  namespace: {{ include "setup-platform-bookstack.namespace" $ }}
  labels:
    {{- include "setup-platform-bookstack.labels" $ | nindent 4 }}
    app.kubernetes.io/component: git-credentials
type: Opaque
data:
  {{- if $repo.credentials.username }}
  username: {{ $repo.credentials.username | b64enc | quote }}
  {{- end }}
  {{- if $repo.credentials.password }}
  password: {{ $repo.credentials.password | b64enc | quote }}
  {{- end }}
  {{- if $repo.credentials.token }}
  token: {{ $repo.credentials.token | b64enc | quote }}
  {{- end }}
  {{- if $repo.credentials.sshKey }}
  ssh-privatekey: {{ $repo.credentials.sshKey | b64enc | quote }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}