apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace.name | default "bookstack" }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    {{- include "setup-platform-bookstack.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "setup-platform-bookstack.selectorLabels" . | nindent 4 }}