apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "setup-platform-nexus.fullname" . }}
  namespace: {{ include "setup-platform-nexus.namespace" . }}
  labels:
    {{- include "setup-platform-nexus.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    {{- toYaml .Values.updateStrategy | nindent 4 }}
  selector:
    matchLabels:
      {{- include "setup-platform-nexus.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "setup-platform-nexus.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "setup-platform-nexus.serviceAccountName" . }}
      containers:
        - name: nexus
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: nexus-ui
              containerPort: 8081
              protocol: TCP
          env:
            - name: INSTALL4J_ADD_VM_PARAMS
              value: "-Xms{{ .Values.nexus.jvm.minHeapSize }} -Xmx{{ .Values.nexus.jvm.maxHeapSize }} -XX:MaxDirectMemorySize=2G -Djava.util.prefs.userRoot=/nexus-data/javaprefs"
            - name: NEXUS_SECURITY_RANDOMPASSWORD
              value: "false"
            {{- if .Values.nexus.defaultAdminPassword }}
            - name: NEXUS_ADMIN_PASSWORD
              value: {{ .Values.nexus.defaultAdminPassword | quote }}
            {{- end }}
          livenessProbe:
            httpGet:
              path: /
              port: nexus-ui
            initialDelaySeconds: 120
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 6
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: /
              port: nexus-ui
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
            successThreshold: 1
          startupProbe:
            httpGet:
              path: /
              port: nexus-ui
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 30
            successThreshold: 1
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: nexus-data
              mountPath: {{ .Values.nexus.dataDir }}
      volumes:
        - name: nexus-data
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "setup-platform-nexus.fullname" . }}-data
          {{- else }}
          emptyDir:
            sizeLimit: 10Gi
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}