{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "setup-platform-nexus.fullname" . }}-data
  namespace: {{ include "setup-platform-nexus.namespace" . }}
  labels:
    {{- include "setup-platform-nexus.labels" . | nindent 4 }}
    app.kubernetes.io/component: storage
  {{- with .Values.persistence.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass }}
  {{- end }}
{{- end }}