# Configuration for OpenShift console plugins
console_plugins:
  enabled: false  # Opcional (si no se define, los plugins no se configuran)
  syncwave: 5  # Opcional (valor predeterminado: 5)
  plugins: []  # Opcional (si está vacío, no se configura ningún plugin)
  job_namespace: kube-system  # Opcional (valor predeterminado: kube-system)
  job_service_account: enable-console-plugin-sa  # Opcional (valor predeterminado: enable-console-plugin-sa)
  job_service_account_role: enable-console-plugin-role  # Opcional (valor predeterminado: enable-console-plugin-role)
  job_service_account_crb: enable-console-plugin-crb  # Opcional (valor predeterminado: enable-console-plugin-crb)

# Configuration for Operators
operators:
  my-operator:
    enabled: false  # Enable or disable the operator deployment
    syncwave: 0  # Syncwave for operator deployment (default: 0)
    namespace:
      name: openshift-operators-redhat  # Namespace where the operator will be installed
      descr: ""  # Optional: Description of the namespace
      displayname: ""  # Optional: Display name of the namespace
      create: true  # Whether to create the namespace (default: true)
    subscription:
      channel: stable  # Subscription channel (default: stable)
      approval: Automatic  # Approval mode: Manual or Automatic (default: Automatic)
      operatorName: loki-operator  # Name of the operator to install
      source: redhat-operators  # Operator source (default: redhat-operators)
      sourceNamespace: openshift-marketplace  # Namespace of the source (default: openshift-marketplace)
      config:
        env:  # Additional environment variables
          - name: FIRST_ENV_PARAMETER
            value: ThisIsRequired
          - name: SECOND_ENV_PARAMETER
            value: 'true'
        resources:  # Resource requests and limits for the subscription
          limits:
            cpu: 100m
            memory: 1Gi
          requests:
            cpu: 400m
            memory: 300Mi
        tolerations:  # Node tolerations
          - effect: NoSchedule
            key: node-role.kubernetes.io/infra
            value: reserved
          - effect: NoExecute
            key: node-role.kubernetes.io/infra
            value: reserved
        nodeSelector:  # Node selector for scheduling
          key: node-role.kubernetes.io/infra
          value: ""
    operatorgroup:
      create: false  # Whether to create an OperatorGroup (default: false)
      notownnamespace: true  # Monitor only its own namespace (default: true)