# Red Hat AMQ Streams (Kafka) Configuration

# Operator installation
operator:
  enabled: true
  channel: stable
  namespace: openshift-operators
  installPlanApproval: Automatic

# Namespace configuration
namespace:
  create: true
  name: kafka
  
# Kafka cluster configuration
kafka:
  # Cluster creation
  cluster:
    enabled: true
    name: my-cluster
    
    # Kafka version
    version: 3.8.0
    
    # Kafka brokers
    replicas: 3
    
    # Kafka broker storage
    storage:
      type: persistent-claim
      size: 10Gi
      storageClass: ""
      deleteClaim: false
      
    # Resource configuration
    resources:
      requests:
        memory: "1Gi"
        cpu: "500m"
      limits:
        memory: "2Gi"
        cpu: "1000m"
        
    # JVM settings
    jvmOptions:
      "-Xms": "1G"
      "-Xmx": "1G"
      
    # Configuration overrides
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
      inter.broker.protocol.version: "3.8"
        
  # ZooKeeper configuration
  zookeeper:
    replicas: 3
    storage:
      type: persistent-claim
      size: 5Gi
      storageClass: ""
      deleteClaim: false
      
    resources:
      requests:
        memory: "512Mi"
        cpu: "250m"
      limits:
        memory: "1Gi"
        cpu: "500m"
        
  # Entity Operator (Topic & User management)
  entityOperator:
    topicOperator:
      enabled: true
      resources:
        requests:
          memory: "256Mi"
          cpu: "100m"
        limits:
          memory: "512Mi"
          cpu: "500m"
    userOperator:
      enabled: true
      resources:
        requests:
          memory: "256Mi"
          cpu: "100m"
        limits:
          memory: "512Mi"
          cpu: "500m"

# Kafka Connect (optional)
kafkaConnect:
  enabled: false
  name: my-connect-cluster
  replicas: 3
  
# Topics configuration
topics:
  enabled: true
  topics:
    - name: demo-topic
      partitions: 3
      replicas: 3
      config:
        retention.ms: 604800000  # 7 days
        segment.ms: 86400000     # 1 day
        
    - name: events-topic
      partitions: 6
      replicas: 3
      config:
        retention.ms: 2592000000  # 30 days
        cleanup.policy: compact

# Users configuration
users:
  enabled: false
  users:
    - name: kafka-user
      type: tls
      authorization:
        type: simple
        acls:
          - resource:
              type: topic
              name: "*"
            operations: [Read, Write, Describe]

# Monitoring
monitoring:
  enabled: false
  prometheus:
    enabled: false
    
# Network policies
networkPolicy:
  enabled: false
  
# Pod Disruption Budget
podDisruptionBudget:
  enabled: true
  kafka:
    maxUnavailable: 1
  zookeeper:
    maxUnavailable: 1

# Advanced configuration
advanced:
  # Custom annotations
  annotations: {}
  
  # Custom labels
  labels: {}
  
  # Node selector
  nodeSelector: {}
  
  # Tolerations
  tolerations: []
  
  # Affinity rules
  affinity: {}