name: Publish Charts

on:
  push:
    branches: [main]
    paths:
      - 'charts/**'
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Package and Publish
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Checkout gh-pages
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.13.2

      - name: Add repositories
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo add codecentric https://codecentric.github.io/helm-charts
          helm repo add tjungbauer https://charts.stderr.at/
          
          # Try to add our own repo if it exists (for dependencies)  
          helm repo add jeanlopezxyz https://jeanlopezxyz.github.io/helm-charts 2>/dev/null || echo "Own repository not yet available"
          
          helm repo update

      - name: Package charts
        run: |
          mkdir -p packages
          
          # First pass: Package charts without dependencies
          echo "=== First pass: Charts without external dependencies ==="
          for chart in charts/*/; do
            if [ -f "$chart/Chart.yaml" ]; then
              chart_name=$(basename $chart)
              echo "Checking $chart_name"
              
              # Skip charts with external dependencies on first pass
              if ! grep -q "repository:" "$chart/Chart.yaml" 2>/dev/null; then
                echo "Packaging $chart_name (no external deps)"
                helm package "$chart" --destination packages
              else
                echo "Skipping $chart_name (has external deps)"
              fi
            fi
          done
          
          # Second pass: Package charts with dependencies (best effort)
          echo "=== Second pass: Charts with dependencies ==="
          for chart in charts/*/; do
            if [ -f "$chart/Chart.yaml" ]; then
              chart_name=$(basename $chart)
              
              # Only process charts with dependencies
              if grep -q "repository:" "$chart/Chart.yaml" 2>/dev/null; then
                echo "Attempting to package $chart_name"
                
                # Try to update dependencies, continue on failure
                if helm dependency update "$chart" 2>/dev/null; then
                  echo "Dependencies updated successfully for $chart_name"
                else
                  echo "Warning: Could not update dependencies for $chart_name, packaging anyway"
                fi
                
                # Package the chart
                if helm package "$chart" --destination packages 2>/dev/null; then
                  echo "Successfully packaged $chart_name"
                else
                  echo "Warning: Failed to package $chart_name"
                fi
              fi
            fi
          done
          
          echo "=== Packaging summary ==="
          ls -la packages/ || echo "No packages created"

      - name: Update repository
        run: |
          cd gh-pages
          
          # Copy chart packages if they exist
          if ls ../packages/*.tgz 1> /dev/null 2>&1; then
            echo "Copying chart packages"
            cp ../packages/*.tgz .
          else
            echo "No chart packages found"
          fi
          
          # Copy Artifact Hub metadata
          cp ../artifacthub-repo.yml . 2>/dev/null || true
          
          # Generate Helm repository index
          helm repo index . --url https://jeanlopezxyz.github.io/helm-charts
          
          # Verify Artifact Hub compatibility
          if command -v ah &> /dev/null; then
            ah lint --kind helm || echo "Artifact Hub linting completed"
          fi
          
          echo "=== Repository contents ==="
          ls -la

      - name: Copy website assets
        run: |
          cd gh-pages
          mkdir -p assets
          cp ../assets/* assets/ 2>/dev/null || true

      - name: Create simple HTML file
        run: |
          cd gh-pages
          cat > index.html << 'EOF'
          <!DOCTYPE html>
          <html>
          <head>
              <title>Helm Charts Repository</title>
              <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
              <style>
                  body { font-family: Arial, sans-serif; }
                  .hero { background: linear-gradient(135deg, #0f172a 0%, #1e40af 100%); color: white; padding: 2rem; }
              </style>
          </head>
          <body>
              <div class="hero text-center">
                  <h1>Helm Charts Repository</h1>
                  <p>Enterprise repository for Red Hat environments</p>
              </div>
              
              <div class="container my-5">
                  <h2 class="text-center mb-4">Available Charts</h2>
                  
                  <div class="row">
                      <div class="col-md-6 mb-4">
                          <div class="card border-primary">
                              <div class="card-header bg-primary text-white">
                                  <h5>helper-operator</h5>
                                  <span class="badge bg-light text-dark">v1.0.28</span>
                              </div>
                              <div class="card-body">
                                  <p>Meta-chart for installing operators</p>
                                  <a href="https://github.com/jeanlopezxyz/helm-charts/tree/main/charts/helper-operator" class="btn btn-sm btn-outline-secondary me-2">GitHub</a>
                                  <a href="https://jeanlopezxyz.github.io/helm-charts/helper-operator-1.0.28.tgz" class="btn btn-sm btn-success">Download</a>
                                  <div class="mt-3 p-2 bg-light">
                                      <code>helm install operator jeanlopezxyz/helper-operator</code>
                                  </div>
                              </div>
                          </div>
                      </div>
                      
                      <div class="col-md-6 mb-4">
                          <div class="card border-danger">
                              <div class="card-header bg-danger text-white">
                                  <h5>setup-rh-pipelines</h5>
                                  <span class="badge bg-light text-dark">v1.0.4</span>
                              </div>
                              <div class="card-body">
                                  <p>Red Hat Pipelines (Tekton) for CI/CD</p>
                                  <a href="https://github.com/jeanlopezxyz/helm-charts/tree/main/charts/setup-rh-pipelines" class="btn btn-sm btn-outline-secondary me-2">GitHub</a>
                                  <a href="https://jeanlopezxyz.github.io/helm-charts/setup-rh-pipelines-1.0.4.tgz" class="btn btn-sm btn-success">Download</a>
                                  <div class="mt-3 p-2 bg-light">
                                      <code>helm install pipelines jeanlopezxyz/setup-rh-pipelines</code>
                                  </div>
                              </div>
                          </div>
                      </div>
                      
                      <div class="col-md-6 mb-4">
                          <div class="card border-success">
                              <div class="card-header bg-success text-white">
                                  <h5>setup-rh-console</h5>
                                  <span class="badge bg-light text-dark">v1.0.6</span>
                              </div>
                              <div class="card-body">
                                  <p>Enhanced OpenShift Console operator</p>
                                  <a href="https://github.com/jeanlopezxyz/helm-charts/tree/main/charts/setup-rh-console" class="btn btn-sm btn-outline-secondary me-2">GitHub</a>
                                  <a href="https://jeanlopezxyz.github.io/helm-charts/setup-rh-console-1.0.6.tgz" class="btn btn-sm btn-success">Download</a>
                                  <div class="mt-3 p-2 bg-light">
                                      <code>helm install console jeanlopezxyz/setup-rh-console</code>
                                  </div>
                              </div>
                          </div>
                      </div>
                      
                      <div class="col-md-6 mb-4">
                          <div class="card border-warning">
                              <div class="card-header bg-warning">
                                  <h5>setup-app-openshift-ai-asistant</h5>
                                  <span class="badge bg-dark">v2.0.0</span>
                              </div>
                              <div class="card-body">
                                  <p>AI-powered assistant with OpenShift AI</p>
                                  <a href="https://github.com/jeanlopezxyz/helm-charts/tree/main/charts/setup-app-openshift-ai-asistant" class="btn btn-sm btn-outline-secondary me-2">GitHub</a>
                                  <a href="https://jeanlopezxyz.github.io/helm-charts/setup-app-openshift-ai-asistant-2.0.0.tgz" class="btn btn-sm btn-success">Download</a>
                                  <div class="mt-3 p-2 bg-light">
                                      <code>helm install ai-asistant jeanlopezxyz/setup-app-openshift-ai-asistant</code>
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
          </body>
          </html>
          EOF

      - name: Deploy
        run: |
          cd gh-pages
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
          git add .
          git commit -m "Update charts and website"
          git push origin gh-pages