name: Publish Charts

on:
  push:
    branches: [main]
    paths:
      - 'charts/**'
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Package and Publish
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Checkout gh-pages
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.13.2

      - name: Add repositories
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo add codecentric https://codecentric.github.io/helm-charts
          helm repo add tjungbauer https://charts.stderr.at/
          helm repo update

      - name: Package charts
        run: |
          mkdir -p packages
          for chart in charts/*/; do
            if [ -f "$chart/Chart.yaml" ]; then
              echo "Packaging $(basename $chart)"
              helm dependency update "$chart" 2>/dev/null || true
              helm package "$chart" --destination packages
            fi
          done

      - name: Update repository
        run: |
          cd gh-pages
          cp ../packages/*.tgz . 2>/dev/null || true
          helm repo index . --url https://jeanlopezxyz.github.io/helm-charts

      - name: Copy website assets
        run: |
          cd gh-pages
          mkdir -p assets
          cp ../assets/* assets/ 2>/dev/null || true

      - name: Generate website
        run: |
          cd gh-pages
          cat > index.html << 'EOF'
          <!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>DemoJam Helm Charts</title>
              <link href="assets/styles.css" rel="stylesheet">
              <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
          </head>
          <body>
              <header class="hero">
                  <div class="container">
                      <h1><i class="fas fa-ship"></i> DemoJam Helm Charts</h1>
                      <p>Enterprise repository for Red Hat DemoJam 2026</p>
                      <div class="repo-url">
                          <code>helm repo add demojam https://jeanlopezxyz.github.io/helm-charts</code>
                          <button onclick="copyToClipboard(this.previousElementSibling.textContent)">
                              <i class="fas fa-copy"></i>
                          </button>
                      </div>
                  </div>
              </header>
              
              <main class="container">
                  <section class="charts-section">
                      <h2>Available Charts</h2>
                      <div id="charts-container" class="charts-grid">
                          <!-- Charts will be loaded here by JavaScript -->
                      </div>
                  </section>
                  
                  <section class="instructions">
                      <h2>Quick Start</h2>
                      <div class="code-block">
                          <pre><code># Add the repository
          helm repo add demojam https://jeanlopezxyz.github.io/helm-charts

          # Update repositories
          helm repo update

          # List available charts
          helm search repo demojam

          # Install a chart
          helm install my-release demojam/CHART-NAME</code></pre>
                      </div>
                  </section>
              </main>
              
              <footer>
                  <div class="container">
                      <p>&copy; 2025 Red Hat DemoJam. Licensed under MIT.</p>
                  </div>
              </footer>
              
              <script src="assets/scripts.js"></script>
              <script>
                  function copyToClipboard(text) {
                      navigator.clipboard.writeText(text).then(() => {
                          const btn = event.target.closest('button');
                          const original = btn.innerHTML;
                          btn.innerHTML = '<i class="fas fa-check"></i>';
                          setTimeout(() => btn.innerHTML = original, 2000);
                      });
                  }
                  
                  // Load charts when page loads
                  document.addEventListener('DOMContentLoaded', loadCharts);
              </script>
          </body>
          </html>
          EOF

      - name: Deploy
        run: |
          cd gh-pages
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
          git add .
          git commit -m "Update charts and website"
          git push origin gh-pages