name: Publish Charts

on:
  push:
    branches: [main]
    paths:
      - 'charts/**'
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Package and Publish
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Checkout gh-pages
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.13.2

      - name: Add repositories
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo add codecentric https://codecentric.github.io/helm-charts
          helm repo add tjungbauer https://charts.stderr.at/
          
          # Try to add our own repo if it exists (for dependencies)  
          helm repo add jeanlopezxyz https://jeanlopezxyz.github.io/helm-charts 2>/dev/null || echo "Own repository not yet available"
          
          helm repo update

      - name: Package charts
        run: |
          mkdir -p packages
          
          # First pass: Package charts without dependencies
          echo "=== First pass: Charts without external dependencies ==="
          for chart in charts/*/; do
            if [ -f "$chart/Chart.yaml" ]; then
              chart_name=$(basename $chart)
              echo "Checking $chart_name"
              
              # Skip charts with external dependencies on first pass
              if ! grep -q "repository:" "$chart/Chart.yaml" 2>/dev/null; then
                echo "Packaging $chart_name (no external deps)"
                helm package "$chart" --destination packages
              else
                echo "Skipping $chart_name (has external deps)"
              fi
            fi
          done
          
          # Second pass: Package charts with dependencies (best effort)
          echo "=== Second pass: Charts with dependencies ==="
          for chart in charts/*/; do
            if [ -f "$chart/Chart.yaml" ]; then
              chart_name=$(basename $chart)
              
              # Only process charts with dependencies
              if grep -q "repository:" "$chart/Chart.yaml" 2>/dev/null; then
                echo "Attempting to package $chart_name"
                
                # Try to update dependencies, continue on failure
                if helm dependency update "$chart" 2>/dev/null; then
                  echo "Dependencies updated successfully for $chart_name"
                else
                  echo "Warning: Could not update dependencies for $chart_name, packaging anyway"
                fi
                
                # Package the chart
                if helm package "$chart" --destination packages 2>/dev/null; then
                  echo "Successfully packaged $chart_name"
                else
                  echo "Warning: Failed to package $chart_name"
                fi
              fi
            fi
          done
          
          echo "=== Packaging summary ==="
          ls -la packages/ || echo "No packages created"

      - name: Update repository
        run: |
          cd gh-pages
          
          # Copy chart packages if they exist
          if ls ../packages/*.tgz 1> /dev/null 2>&1; then
            echo "Copying chart packages"
            cp ../packages/*.tgz .
          else
            echo "No chart packages found"
          fi
          
          # Copy Artifact Hub metadata
          cp ../artifacthub-repo.yml . 2>/dev/null || true
          
          # Generate Helm repository index
          helm repo index . --url https://jeanlopezxyz.github.io/helm-charts
          
          # Verify Artifact Hub compatibility
          if command -v ah &> /dev/null; then
            ah lint --kind helm || echo "Artifact Hub linting completed"
          fi
          
          echo "=== Repository contents ==="
          ls -la

      - name: Copy website assets
        run: |
          cd gh-pages
          mkdir -p assets
          cp ../assets/* assets/ 2>/dev/null || true

      - name: Generate website
        run: |
          cd gh-pages
          cat > index.html << 'HTMLEOF'
          <!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>Helm Charts Repository</title>
              <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
              <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" rel="stylesheet">
              <style>
                  .hero { background: linear-gradient(135deg, #0f172a 0%, #1e40af 100%); color: white; padding: 3rem 0; }
                  .chart-card { transition: transform 0.3s; }
                  .chart-card:hover { transform: translateY(-5px); }
              </style>
          </head>
          <body>
              <header class="hero">
                  <div class="container text-center">
                      <h1 class="display-4 fw-bold mb-3"><i class="fas fa-ship me-3"></i>Helm Charts Repository</h1>
                      <p class="lead">Enterprise repository for Red Hat environments</p>
                      <div class="bg-white bg-opacity-10 rounded p-3 d-inline-block mt-3">
                          <code class="text-white">helm repo add jeanlopezxyz https://jeanlopezxyz.github.io/helm-charts</code>
                      </div>
                  </div>
              </header>
              
              <main class="container my-5">
                  <section class="charts-section">
                      <h2 class="text-center mb-5">Available Charts</h2>
                      
                      <div class="row g-4">
                          <div class="col-md-6">
                              <div class="card h-100 shadow-lg border-primary border-3 chart-card">
                                  <div class="card-header bg-primary text-white text-center">
                                      <h4 class="mb-0"><i class="fas fa-cogs me-2"></i>helper-operator</h4>
                                      <span class="badge bg-danger">v1.0.28</span>
                                  </div>
                                  <div class="card-body">
                                      <p class="card-text">Meta-chart for installing operators with standardized configuration</p>
                                      <div class="mb-3">
                                          <span class="badge bg-secondary me-1">helper</span>
                                          <span class="badge bg-secondary me-1">operator</span>
                                          <span class="badge bg-secondary">automation</span>
                                      </div>
                                      <div class="d-flex gap-2 mb-3">
                                          <a href="https://github.com/jeanlopezxyz/helm-charts/tree/main/charts/helper-operator" target="_blank" class="btn btn-outline-secondary btn-sm">
                                              <i class="fab fa-github me-1"></i>Source
                                          </a>
                                          <a href="https://jeanlopezxyz.github.io/helm-charts/helper-operator-1.0.28.tgz" class="btn btn-success btn-sm">
                                              <i class="fas fa-download me-1"></i>Download
                                          </a>
                                      </div>
                                      <div class="alert alert-dark mb-0">
                                          <code>helm install operator jeanlopezxyz/helper-operator</code>
                                      </div>
                                  </div>
                              </div>
                          </div>
                          
                          <div class="col-md-6">
                              <div class="card h-100 shadow-lg border-danger border-3 chart-card">
                                  <div class="card-header bg-danger text-white text-center">
                                      <h4 class="mb-0"><i class="fas fa-project-diagram me-2"></i>setup-rh-pipelines</h4>
                                      <span class="badge bg-warning text-dark">v1.0.3</span>
                                  </div>
                                  <div class="card-body">
                                      <p class="card-text">Red Hat Pipelines (Tekton) for CI/CD automation</p>
                                      <div class="mb-3">
                                          <span class="badge bg-secondary me-1">pipelines</span>
                                          <span class="badge bg-secondary me-1">tekton</span>
                                          <span class="badge bg-secondary">ci-cd</span>
                                      </div>
                                      <div class="d-flex gap-2 mb-3">
                                          <a href="https://github.com/jeanlopezxyz/helm-charts/tree/main/charts/setup-rh-pipelines" target="_blank" class="btn btn-outline-secondary btn-sm">
                                              <i class="fab fa-github me-1"></i>Source
                                          </a>
                                          <a href="https://jeanlopezxyz.github.io/helm-charts/setup-rh-pipelines-1.0.3.tgz" class="btn btn-success btn-sm">
                                              <i class="fas fa-download me-1"></i>Download
                                          </a>
                                      </div>
                                      <div class="alert alert-dark mb-0">
                                          <code>helm install pipelines jeanlopezxyz/setup-rh-pipelines</code>
                                      </div>
                                  </div>
                              </div>
                          </div>
                          
                          <div class="col-md-6">
                              <div class="card h-100 shadow-lg border-success border-3 chart-card">
                                  <div class="card-header bg-success text-white text-center">
                                      <h4 class="mb-0"><i class="fas fa-desktop me-2"></i>setup-rh-console</h4>
                                      <span class="badge bg-warning text-dark">v1.0.5</span>
                                  </div>
                                  <div class="card-body">
                                      <p class="card-text">Enhanced OpenShift Console operator with customizations</p>
                                      <div class="mb-3">
                                          <span class="badge bg-secondary me-1">console</span>
                                          <span class="badge bg-secondary me-1">ui</span>
                                          <span class="badge bg-secondary">openshift</span>
                                      </div>
                                      <div class="d-flex gap-2 mb-3">
                                          <a href="https://github.com/jeanlopezxyz/helm-charts/tree/main/charts/setup-rh-console" target="_blank" class="btn btn-outline-secondary btn-sm">
                                              <i class="fab fa-github me-1"></i>Source
                                          </a>
                                          <a href="https://jeanlopezxyz.github.io/helm-charts/setup-rh-console-1.0.5.tgz" class="btn btn-success btn-sm">
                                              <i class="fas fa-download me-1"></i>Download
                                          </a>
                                      </div>
                                      <div class="alert alert-dark mb-0">
                                          <code>helm install console jeanlopezxyz/setup-rh-console</code>
                                      </div>
                                  </div>
                              </div>
                          </div>
                          
                          <div class="col-md-6">
                              <div class="card h-100 shadow-lg border-warning border-3 chart-card">
                                  <div class="card-header bg-warning text-dark text-center">
                                      <h4 class="mb-0"><i class="fas fa-robot me-2"></i>setup-app-openshift-ai-asistant</h4>
                                      <span class="badge bg-danger">v2.0.0</span>
                                  </div>
                                  <div class="card-body">
                                      <p class="card-text">AI-powered assistant with OpenShift AI and RAG architecture</p>
                                      <div class="mb-3">
                                          <span class="badge bg-secondary me-1">ai</span>
                                          <span class="badge bg-secondary me-1">openshift</span>
                                          <span class="badge bg-secondary">assistant</span>
                                      </div>
                                      <div class="d-flex gap-2 mb-3">
                                          <a href="https://github.com/jeanlopezxyz/helm-charts/tree/main/charts/setup-app-openshift-ai-asistant" target="_blank" class="btn btn-outline-secondary btn-sm">
                                              <i class="fab fa-github me-1"></i>Source
                                          </a>
                                          <a href="https://jeanlopezxyz.github.io/helm-charts/setup-app-openshift-ai-asistant-2.0.0.tgz" class="btn btn-success btn-sm">
                                              <i class="fas fa-download me-1"></i>Download
                                          </a>
                                      </div>
                                      <div class="alert alert-dark mb-0">
                                          <code>helm install ai-asistant jeanlopezxyz/setup-app-openshift-ai-asistant</code>
                                      </div>
                                  </div>
                              </div>
                          </div>
                      </div>
                  </section>
                  
                  <section class="my-5">
                      <div class="card">
                          <div class="card-header bg-info text-white">
                              <h3 class="mb-0"><i class="fas fa-rocket me-2"></i>Quick Start</h3>
                          </div>
                          <div class="card-body">
                              <pre class="bg-dark text-success p-3 rounded"><code># Add the repository
helm repo add jeanlopezxyz https://jeanlopezxyz.github.io/helm-charts

# Update repositories  
helm repo update

# List available charts
helm search repo jeanlopezxyz

# Install a chart
helm install my-release jeanlopezxyz/CHART-NAME</code></pre>
                          </div>
                      </div>
                      
                      <div class="alert alert-info mt-4">
                          <h5><i class="fas fa-external-link-alt me-2"></i>Also available on Artifact Hub</h5>
                          <p class="mb-0">Browse and discover our charts on <a href="https://artifacthub.io/packages/search?repo=jeanlopezxyz" target="_blank" class="alert-link">Artifact Hub</a></p>
                      </div>
                  </section>
              </main>
              
              <footer class="bg-dark text-white py-4">
                  <div class="container text-center">
                      <p class="mb-0">&copy; 2025 Red Hat. Licensed under MIT.</p>
                  </div>
              </footer>
              
              <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
          </body>
          </html>
          HTMLEOF

      - name: Deploy
        run: |
          cd gh-pages
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
          git add .
          git commit -m "Update charts and website"
          git push origin gh-pages